### PR TITLE
Clean up Python 2 styled code

### PR DESCRIPTION
**Pull request by Cito**
Some clean-up since paste only supports Python 3 nowadays:

- in Python 3, we don't need to inherit from object
- [avoid bare excepts](https://stackoverflow.com/questions/54948548/what-is-wrong-with-using-a-bare-except)
- unify the use of "no default" sentinels inside paste
- source code encodings don't need to be specified

### CODE REVIEW

**Comment by cdent** [comment]
Are these kind of cleanups worthwhile if we're trying to dissuade the use of paste?

Also if we're trying to keep it as stable as possible, we want to change it as little as possible, don't we?

If, on the other hand, we want to sort of bring it back to life, then these sorts of changes are warranted, but I don't know that we've made that decision.

Are _you_ interested in taking it in that direction?

**Comment by Cito** [comment]
No, I don't want to bring it back to life. Just some cheap clean-up before this is retired for good.

But you may decide. If you think it's not worthwile, just close this.

Btw, I did some fixing/cleanup in PySourceColor, but noticed this code is broken beyond despair. It contain bugs and code that cannot run in Python 3 (e.g. calls tokenize with a second parameter that only existed in Python2) , was written for Python 2 as input, and outputs XHTML instead of HTML5.

The only reasonable fix in my view would be to completely replace it with Pygments. If you think that is still worthwile, I would submit a PR, otherwise we need to leave it in this broken state.

**Comment by Cito** [comment]
Looked a bit deeper and was able to fix the issue with the tokenizer. You can call the PySourceColor module on the command line to verify that it was broken before and now works (with the caveats mentioned above).

So I think this whole PR is worthwile to merge. But will end working on paste after this.

**Comment by Cito** [comment]
Btw, another cheap fix of broken Python 2 code is #68 - this is also worthwile to be fixed.

**Comment by cdent** [comment]
nice work, thanks

**Pull request merged**
