### PR TITLE
Replace use of imp with importlib.util

### LINKED ISSUE #75: Replace deprecated imp module with importlib
This project uses the [`imp` module](https://docs.python.org/3/library/imp.html) which has been deprecated since Python 3.4 and removed in 3.12:

* Raised `PendingDeprecationWarning` since [3.4 (2014)](https://github.com/python/cpython/commit/e4f41deccf94ccc798b1eb1f44657ade66669a60)
* Raised `DeprecationWarning` since [3.5 (2015)](https://github.com/python/cpython/commit/c0d91aff9a3b91307b26e8b7c34dfbf27bbdd43a)
* Updated `DeprecationWarning` to say removal in 3.12 since [3.10 (2021)](https://github.com/python/cpython/commit/dc6d3e1e4c0c1e4b2210edab8fb4762569dc2936)
* Removal planned for [3.12](https://github.com/python/cpython/issues/98040) [(2023)](https://github.com/python/cpython/pull/98573)

Python 3.12 is [set for release on 2023-10-02](https://devguide.python.org/versions/) and this library is one of the [top 5,000 most-downloaded from PyPI](https://hugovk.github.io/top-pypi-packages/).

Please could you upgrade to use `importlib`? The [`imp` docs](https://docs.python.org/3.11/library/imp.html) have suggestions on what to use to replace each function and constant.

### PR DESCRIPTION
**Pull request by cdent**
imp is deprecated and will go away in Python 3.12 (which is very soon).

This implementation based on the importlib docs [1] and passes the quite robust tests that are already present for the urlparser module. Unfortunately there's no good way to be 100% certain that this works for all the many ways that Paste can do an import. So this patch is mostly hoping that test coverage is sufficient.

[1] https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly

Fixes #75

### CODE REVIEW

**Comment by cdent** [comment]
This is going to fail in python 2.7, working on a workaround.

**Comment by hugovk** [comment]
Looks about right and tests pass with Python 3.11 (except for a cgi `DeprecationWarning` failing `test_cgiapp.py`).

I noticed Python 2.7 is still listed in `.travis.yml` and `tox.ini`.

Do you still support it? If so, you'll probably also need the old method. (I recommend dropping 2.7.)

**Comment by cdent** [comment]
I'd _love_ to drop 2.7 but a significant portion of people who still use Paste (which they shouldn't) are stuck in legacy situations.

The plan is to leave the old way in for python2, currently working through some issues with GitHub actions to get automated testing set up ...

**Comment by hugovk** [comment]
Heads up that GitHub Actions is removing Python 2.7 in a couple of weeks: https://github.com/actions/runner-images/issues/7401

**Comment by cdent** [comment]
That's alright, I still need to get the rest of the testing stuff set up anyway. And I have a local machine where I can do 2.7 testing.

**Pull request merged**
