### PR TITLE
If Python doesn't know about a request's charset, fall back to the default.

### PR DESCRIPTION
**Pull request by benjaminp**

### CODE REVIEW

**Comment by cdent** [comment]
I'm not sure about this one. I tend to think paste should not be the one deciding to transform a content type, instead passing it on and letting the app decide. However given the amount of transforming that paste is doing in WSGIRequest, maybe what you're doing is the best solution.

Or, perhaps it should be causing a 415 if the content-type is bogus?

I'm happy to have this one if you can provide a bit more explanation/justification for why.

**Comment by benjaminp** [comment]
Yeah, if I was encountering this problem by itself I would say returning a client error is the right fix. Unfortunately, I have web clients setting request headers like `Content-type: text/plain; charset=bogus` as a hack to avoid browser CORS pre-flight requests. This causes accessing `request.params` to explode because `cgi.FieldStorage` doesn't like invalid encodings. (It's also very fragile on Python 2; apparently, this was only working on Python 2 because no one ever accessed any keys in `requests.params` for these requests.)

Under this PR, the app can determine something funny is going on by checking if `request.charset != request.determine_browser_charset()`. 

I would understand if you think this is all too horrible to support. I can probably work around it elsewhere.

**Comment by benjaminp** [comment]
Thinking about this more, I've become less and less sure, so I withdraw this for the moment.

**Comment by cdent** [comment]
If it comes back in some other form, please feel free to try again. Thanks again for your continued work on these things.

**Pull request closed without merging**
