### PR TITLE
misc bugs + please pyflakes

### PR DESCRIPTION
**Pull request by a-detiste**
I use pyflakes to verify I'm not introducing regressions.

Here's a real bug I have no idea how to fix:

```
./paste/debug/watchthreads.py:279:16: undefined name 'environ_template'
./paste/debug/watchthreads.py:290:17: undefined name 'environ_template'
./paste/debug/watchthreads.py:295:17: undefined name 'environ_template'
```

### CODE REVIEW

**Comment by cdent** [comment]
What the state of this?

Still issues with `undefined name 'environ_template'`? Or did that get resolved?

**Comment by a-detiste** [comment]
`undefined name 'environ_template``: this has always been broken since the first/only commit and I have no idead what author tried to do. I fixed the other bugs I could.

**Comment by cdent** [comment]
Will look into the `environ_template` thing and and do a new release soon.

Thanks again for your ongoing assistance. Very much appreciated.

**Comment by a-detiste** [comment]
The previous Debian maintainer left so I adopted this one package.
We have automated test triggered on all reverse-dependencies on upgrade.
I'll ping you if things needs more fixing.

**Comment by cdent** [comment]
Looks like the `format_environ` that contains `environ_template` is dead code not used by the surrounding WSGI app.

I would guess it became stale some time before I adopted paste.

I'll do some more thorough searching and remove it becomes clear nothing is using it.

**Pull request merged**
