### PR TITLE
remove most python2 compatibility

### PR DESCRIPTION
**Pull request by a-detiste**
I'm also trying to please `pyflakes` to see where real errors are.

### CODE REVIEW

**Comment by cdent** [comment]
Thanks, again, very much.

**Comment by a-detiste** [comment]
There are still remains of `six` to clean up: six.ensure_text( & six.ensure_binary( are especialy hard to fix usually. I'll have a look at it later. In the meantime 3.8.0 is packaged for Debian. Greetings

**Comment by a-detiste** [comment]
A bit of typing annotations would help .... I will see

**Comment by cdent** [comment]
> A bit of typing annotations would help .... I will see

I'd prefer we _not_ put typing annotations into Paste.

Doing so implies a commitment to Paste longevity, and I don't think we want to do that. At this stage in its lifecycle paste should be used by people who have to for maintaining existing (and old) projects. It should never be chosen for something new.

**Comment by a-detiste** [comment]
Ok I respect your point of view. I'll keep it simple.

**Pull request merged**
